# action.yml
name: 'Check Server'
description: 'Check URL and Host from a JSON file'
inputs:
  filename:
    description: 'Filename of the JSON file'
    required: false
    default: './urls.json'
  protocol:
    description: 'http or https'
    required: false
    default: 'https'
  slack:
    description: 'slack webhook token'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.filename }}
    - ${{ inputs.protocol }}
    - ${{ inputs.slack }}