# action.yml
name: 'Check Server'
description: 'Check URL and Host from a JSON file'
inputs:
  filename:
    description: 'Filename of the JSON file'
    required: false
    default: './urls.json'
  protocol:
    description: 'http or https'
    required: false
    default: 'https'
  slack:
    description: 'slack webhook token inside github secret'
    required: true
  reposlack:
    description: 'slack webhook token inside repo'
    required: false
branding:
  icon: 'airplay'
  color: 'blue'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.filename }}
    - ${{ inputs.protocol }}
    - ${{ inputs.slack }}
    - ${{ inputs.reposlack }}