name: simple-server-monitoring

on:
  workflow_dispatch:
  # schedule:
  #   - cron: "0 * * * *"

env:
  SLACK_WEBHOOK: test
  # SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

jobs:
  server-monitoring:
    runs-on: ubuntu-latest
    name: server-monitoring using http request
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check request
        uses: ./  #marketplace에 등록되면 actions/server-monitoring.. 으로 변경
        with:
          filename: './json/url.json'
          protocol: 'https'
          slack: ${{ env.SLACK_WEBHOOK }}
