name: simple-server-monitoring

on:
  workflow_dispatch:
  # schedule:
  #   - cron: "0 * * * *"

env:
  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
  REPO_SLACK_WEBHOOK : ''  #optional env
jobs:
  server-monitoring:
    runs-on: ubuntu-latest
    name: server-monitoring using http request
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install node-fetch
      - name: Check request
        uses: ./ #marketplace에 등록되면 actions/server-monitoring.. 으로 변경
        with:
          filename: "./urls.json"
          protocol: "https"
          slack: ${{ env.SLACK_WEBHOOK }}
          reposlack: ${{ env.REPO_SLACK_WEBHOOK }}
